clinic/Controllers/DoctorController.cs
using System.Text;
using clinic.Data;
using clinic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace clinic.Controllers
{
 
      public class DoctorController : Controller
    {
        private readonly AppDBContext _dbContext;
        private readonly IWebHostEnvironment _environment;

        public DoctorController(AppDBContext dBContext, IWebHostEnvironment environment)
        {
            _dbContext = dBContext;
            _environment = environment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contact()
        {
            EmailToContact emailToContact = new EmailToContact();
            emailToContact.Emails = _dbContext.doctors.Select(p => p.Email).ToList();
          if (HttpContext.Session.Get("Name")!=null)
            TempData["name"] = Convert.ToString(Encoding.UTF8.GetString(HttpContext.Session.Get("Name")));

            return View(emailToContact);
        }
        [HttpPost]
        public IActionResult Contact(EmailToContact emailToContact)
        {
            if (ModelState.IsValid)
            {
                emailToContact.Contact.D_id =
                     _dbContext.doctors.First(d => d.Email == emailToContact.D_Email).Id;
                _dbContext.contacts.Add(emailToContact.Contact);
                _dbContext.SaveChanges();
                return RedirectToAction("Thanks", emailToContact.Contact);
            }


            emailToContact.Emails = _dbContext.doctors.Select(p => p.Email).ToList();
            if (HttpContext.Session.Get("Name") != null)
                TempData["name"] = Convert.ToString(Encoding.UTF8.GetString(HttpContext.Session.Get("Name")));

            return View("contact", emailToContact);
        }
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Registration(Doctor doctor, IFormFile file)
        {
            if (ValidData.CheckEmailPhoen(doctor.Email, doctor.Phone, _dbContext) || doctor.Email == "samwel@gmail.com")
            {
                ModelState.AddModelError("Email", "Email Or Phone Is Used Before  ");
            }
            if (doctor.Phone  == null || doctor.Phone.Length !=11 )
            {
                ModelState.AddModelError("Phone", " Phone must be 11 Number  ");
            }
            if (ModelState.IsValid)
            {
                string path = Path.Combine(_environment.WebRootPath, "img");
                if (file != null)
                {
                    path = Path.Combine(path, file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                doctor.Dr_picture = file.FileName;
                _dbContext.doctors.Add(doctor);
                _dbContext.SaveChanges();
                return RedirectToAction("DashBord" , doctor);
            }
            return View();
        }
        public IActionResult Thanks(Contact contact)
        {
            return View(contact);
        }

        public IActionResult MyTickets (int D_ID)
        {
            TicketToDoctor ticketToDoctor = new TicketToDoctor();
            ticketToDoctor.Tickets = _dbContext.tickets
                .Where(t => t.D_id == D_ID)
                .ToList().Join(_dbContext.patients,
                t => t.P_id, p => p.Id,
                (t, p) => new TicketsData
                { Id = t.Id,
                    P_Name = String.Format($"{p.Fname} {p.Lname}"),
                    Note = t.Note == "" ? "No Note" : t.Note,
                    Status = t.Status
                }).ToList(); 
         
            ticketToDoctor.Doctor = _dbContext.doctors.First(d => d.Id == D_ID); 
            
            return View(ticketToDoctor); 
        }
        public   IActionResult actionResult(int D_ID)
        {
            var doctor = _dbContext.doctors.First(d => d.Id == D_ID);
            return RedirectToAction("DashBord", doctor); 
        }
        public IActionResult DashBord (Doctor doctor)
        {

            HttpContext.Session.SetString("Name", doctor.Fname.ToString());
            HttpContext.Session.SetString("Email", doctor.Email.ToString());

            HttpContext.Session.SetString("D_ID", doctor.Id.ToString());
            TempData["name"] = Convert.ToString(Encoding.UTF8.GetString(HttpContext.Session.Get("Name")));

            return View(doctor); 
        }

        public IActionResult Back ()
        {
            var data = HttpContext.Session.Get("D_ID");
            int id = Convert.ToInt32(Encoding.UTF8.GetString(data));
            var doctor  = _dbContext.doctors.First (d => d.Id == id);   
            return  RedirectToAction ("DashBord", doctor);  
        }
        public IActionResult AddAdmin (int D_ID )
        {
           
            return View(); 
        }
        [HttpPost]
        public IActionResult AddAdmin(Admin admin )
        {
            var data = HttpContext.Session.Get("D_ID");
            int id = Convert.ToInt32(Encoding.UTF8.GetString(data));
            admin.D_id = id;    
            if (ValidData.CheckEmailPhoen(admin.Email , admin.Phone , _dbContext ) || admin.Email == "samwel@gmail.com")
            {
                ModelState.AddModelError("Email", "Email or Phone Is Used Before "); 
            }

            if (ModelState.IsValid) 
            {
                _dbContext.admins.Add(admin);
                var doctor = _dbContext.doctors.First(d=>d.Id == id);
                _dbContext.SaveChanges();
                return RedirectToAction("DashBord", doctor); 
            }
            return View();
        }

        public IActionResult Messages (int D_ID) 
        {
            var data = _dbContext.contacts.Where(d=>d.D_id == D_ID).ToList();   

            return View(data); 
        }
    }
}

clinic/Controllers/PatientController.cs
using System.Text;
using clinic.Data;
using clinic.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace clinic.Controllers
{
    
    public class PatientController : Controller
    {
        private readonly AppDBContext _dbContext;
       
        public PatientController(AppDBContext dBContext ) 
        {
            _dbContext = dBContext; 
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult sign()
        {
            return View();
        }
        [HttpPost]
        public IActionResult sign(Patient patient)
        {
            if (patient.Password != patient.Confirm_Password)
            {
                ModelState.AddModelError("Password", "Password And Confirm Must Be The Same ");
            }

            if ( patient.Phone== null ||  patient.Phone.Length !=11   )
            {
                ModelState.AddModelError("Phone", "Phone Should be 11 Number ");
            }
            if (ValidData.CheckEmailPhoen(patient.Email! , patient.Phone! , _dbContext) || patient.Email == "samwel@gmail.com")
            {
                ModelState.AddModelError("Email", "Email Or Phone Is Used Before  ");
            }

            if (ModelState.IsValid)
            {
                _dbContext.patients.Add(patient);
                _dbContext.SaveChanges();
                return RedirectToAction("MainPage", patient);
            }

            return View();
        }

        public IActionResult MainPage(Patient patient)
        {
            HttpContext.Session.SetString("P_id", patient.Id.ToString());
            HttpContext.Session.SetString("Email", patient.Email!.ToString());
            HttpContext.Session.SetString("Name", patient.Fname!.ToString());
            TempData["name"] = Convert.ToString(Encoding.UTF8.GetString(HttpContext.Session.Get("Name")));

            return View(patient);
        }

        public IActionResult Ticket (int P_ID )
        {
            Ticket_Doctor_Patient ticket_Doctor_Patient = new Ticket_Doctor_Patient();
            ticket_Doctor_Patient.Patient.Id = P_ID;
            ticket_Doctor_Patient.EmailToContact.Emails
                = _dbContext.doctors.Select
                (x => x.Email).ToList();
                 
            return View(ticket_Doctor_Patient);  
        }
        [HttpPost]
        public IActionResult Ticket (Ticket_Doctor_Patient ticket_Doctor_Patient)
        {
            var data = HttpContext.Session.Get("P_id");
            int id = Convert.ToInt32(Encoding.UTF8.GetString(data)); 
            ticket_Doctor_Patient.Ticket.D_id = _dbContext.doctors.
                FirstOrDefault
                (p => p.Email == ticket_Doctor_Patient.EmailToContact.D_Email)!.Id; 
            ticket_Doctor_Patient.Ticket.A_id = null;
            ticket_Doctor_Patient.Ticket.P_id = id; 
           
            if (ticket_Doctor_Patient.Ticket.Note == null)
                  ticket_Doctor_Patient.Ticket.Note = String.Empty;
            
            ticket_Doctor_Patient.Patient = _dbContext.patients.FirstOrDefault(p => p.Id == id)!;
            _dbContext.tickets.Add(ticket_Doctor_Patient.Ticket);
            _dbContext.SaveChanges(); 
            return RedirectToAction("MainPage", ticket_Doctor_Patient.Patient);
        }

        public IActionResult actionResult(int P_ID)
        {
            var patient = _dbContext.patients.First(d => d.Id == P_ID);
            return RedirectToAction("MainPage", patient);
        }
        public IActionResult MyTickets (int P_ID)
        {
            var tickets =
                _dbContext.tickets.Where(t=>t.P_id == P_ID ).ToList();
     
            if (tickets.Count == 0)
            {
                tickets.Add(new Ticket { P_id = P_ID }); 
            }

            return View(tickets);  
        }
        public IActionResult Back()
        {
            var data = HttpContext.Session.Get("P_id");
            int id = Convert.ToInt32(Encoding.UTF8.GetString(data));
            var pa = _dbContext.patients.First(d => d.Id == id);
            return RedirectToAction("MainPage", pa);
        }
    }
}

clinic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Clinic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
    @RenderSection("profile", required: false)
    @RenderSection("docc", required: false)
    @RenderSection("docc", required: false)
    @RenderSection("contact", required: false)
    
</head>
<body>
    <header>
        <nav>
            <div class="container">

                <div>
                    <a class="q"><span>H</span>ealth <span>C</span>are.</a>
                </div>

                <div class="nav">
                    <ul>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Comment">Feed Back</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Doctor" asp-action="Contact">Contact Us</a>
                        </li>

                   
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="login">login</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Patient" asp-action="sign">Sign Up</a>
                        </li> 
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

clinic/Views/Shared/_login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Clinic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
    @RenderSection("profile", required: false)
    @RenderSection("docc", required: false)
    @RenderSection("docc", required: false)
    @RenderSection("contact", required: false)

</head>
<body>
    <header>
        <nav>
            <div class="container">

                <div>
                    <a class="q"><span>H</span>ealth <span>C</span>are.</a>
                </div>

                <div class="nav">
                    <ul>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Comment">Feed Back</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Doctor" asp-action="Contact">Contact Us</a>
                        </li>

                        <li style="font-size : 20px ;color :white ; ">
                          Hi 
                        </li>
                                
                        <li style="font-size : 20px ;color :white ; ">
                            <a asp-controller="Home" asp-action="Check">   @TempData["name"].ToString()  </a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>